# chmod 0000 /Library/Spotlight
# chmod 0000 /System/Library/Spotlight
# chmod 0000 /System/Library/CoreServices/Search.bundle
# chmod 0000 /System/Library/PreferencePanes/Spotlight.prefPane
# chmod 0000 /System/Library/Services/Spotlight.service
# chmod 0000 /usr/bin/mdfind
# chmod 0000 /usr/bin/mdls
# chmod 0000 /usr/bin/mdutil
# chmod 0000 /System/Library/LaunchDaemons/com.apple.metadata.mds.*
# chmod 0000 /System/Library/LaunchAgents/com.apple.metadata.*
